### ISSUE TITLE
"Swift will replace Objective-C for iOS apps" might be inaccurate

### ISSUE THREAD

**Issue by alemangui** [iwasrobbed/Objective-C-CheatSheet#11]
On line **"Read my Swift cheatsheet as well (Swift will replace Objective-C for iOS apps)."**, is there any official source that confirms this? A quick search in Google turned out results that suggest Swift and Objective-C will coexist and there are no plans on deprecating or replacing Objective-C. If this is the case, the statement is pretty missleading and should be removed.

Some links that popped up in a quick Google search:
http://www.quora.com/How-long-will-it-take-for-Swift-to-completely-replace-Objective-C
http://stackoverflow.com/questions/28556371/if-swift-will-replace-objective-c-in-the-future
http://www.huffingtonpost.com/ahmed-eid/apples-swift-is-great-but_b_5492239.html
http://www.lynda.com/articles/swift-1-2-review-buggy

**Comment by alemangui** [comment]
Also here 

**"Swift, Apple's new language to replace Objective-C"**

There is no mention of a replacement in the article linked.

**Comment by iwasrobbed** [comment]
We're going to have to agree to disagree on this one

**Comment by alemangui** [comment]
Do you have any sources? What makes you think Obj-C will be deprecated? (I'm genuinely interested btw, not just being stubborn)

**Comment by raspu** [comment]
I agree with @alemangui here, stating that "Swift will replace Objective-C for iOS apps" is kind of a bold statement. I agree that Swift is going to be embraced by the community, and I believe it may become the de facto language for iOS Development in the (distant?) future. But that is what I believe, I wouldn't call it a fact as you a re doing here. 

Apple is still updating Obj-c, and there's still millions of Apps that are being maintained and developed using Obj-c, I don't see "Swift replacing Obj-c", not yet. I see it as a "more friendlier language" for new developers, and as interesting new thing for us the old ones. 

So, unless you can quote Apple for your "Swift will replace Objective-C for iOS apps" statement, it's just your opinion, not a fact. And I think a "Objective-C-CheatSheet" is not a place for opinions, even if is your Cheat Sheet.

**Comment by iwasrobbed** [comment]
Like I said, we'll have to agree to disagree. Code is an opinion, design patterns are just opinions. The beauty of Github is if you disagree with someone else's "opinion" of how something is done or written, you can fork and create your own.
