### ISSUE TITLE
Minimum / maximum examples for "Long integers"

### ISSUE THREAD

**Issue by Sashom** [iwasrobbed/Objective-C-CheatSheet#18]
Minimum / maximum examples for "Long integers" show in comment 32 bit but they are actually 64 bit?

> // Long (4 bytes for 32-bit, 8 bytes for 64-bit)
> long aLong = -9223372036854775808; **# // 32-bit**
> unsigned long anUnsignedLong = 18446744073709551615; **# // 32-bit**
> NSLog(@"long size: %zu", sizeof(long));

The bold should state "64-bit"

Sasho

**Comment by iwasrobbed** [comment]
Thanks Sasho, can you edit the `README.md` with those changes and open a pull request? https://github.com/iwasrobbed/Objective-C-CheatSheet/blob/master/README.md

<img width="993" alt="screen shot 2018-01-18 at 2 50 25 pm" src="https://user-images.githubusercontent.com/317671/35118185-06738160-fc5f-11e7-9165-a3b753c02fcf.png">
