### ISSUE TITLE
I robbed your CheatSheet

### ISSUE THREAD

**Issue by mulle-nat** [iwasrobbed/Objective-C-CheatSheet#21]
I have [cloned](//github.com/mulle-objc/MulleObjC-Cheat-Sheet) your repo and made a lot of changes to the text, to fit my home-grown variety of Objective-C. But since there is no `License.txt`, this might not be kosher. I would like to know, if you have a problem with that.

**Comment by rob-keepsafe** [comment]
Clone away and change whatever you'd like! All of my personal projects are MIT licensed, but thanks for asking and best of luck to you
